// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AnswerList: typeof import('./../components/AnswerList.vue')['default']
    AnswerOption: typeof import('./../components/AnswerOption.vue')['default']
    GameBox: typeof import('./../components/GameBox.vue')['default']
    MainNavigation: typeof import('./../components/MainNavigation.vue')['default']
    NavigationItem: typeof import('./../components/Navigation/Item.vue')['default']
    NavigationMain: typeof import('./../components/Navigation/Main.vue')['default']
    NavigationSidebarLink: typeof import('./../components/Navigation/SidebarLink.vue')['default']
    NavigationSidebarMain: typeof import('./../components/Navigation/SidebarMain.vue')['default']
    Question: typeof import('../components/QuestionPrompt.vue')['default']
    QuestionBox: typeof import('./../components/QuestionBox.vue')['default']
    QuestionPrompt: typeof import('./../components/QuestionPrompt.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
